<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CommunityToolkit.Mvvm">
      <HintPath>C:\Users\l1763\.nuget\packages\communitytoolkit.mvvm\8.2.2\lib\net6.0\CommunityToolkit.Mvvm.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.data.sqlite.core\8.0.2\lib\net8.0\Microsoft.Data.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite.Core">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.data.sqlite.core\8.0.2\lib\net8.0\Microsoft.Data.Sqlite.Core.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.core">
      <HintPath>C:\Users\l1763\.nuget\packages\sqlitepclraw.core\2.1.6\lib\netstandard2.0\SQLitePCLRaw.core.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.provider.dynamic_cdecl">
      <HintPath>C:\Users\l1763\.nuget\packages\sqlitepclraw.provider.dynamic_cdecl\2.1.6\lib\netstandard2.0\SQLitePCLRaw.provider.dynamic_cdecl.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.bundle_e_sqlite3">
      <HintPath>C:\Users\l1763\.nuget\packages\sqlitepclraw.bundle_e_sqlite3\2.1.6\lib\netstandard2.0\SQLitePCLRaw.bundle_e_sqlite3.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.1\lib\net8.0\Microsoft.Extensions.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.2\lib\net8.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="System.Speech">
      <HintPath>C:\Users\l1763\.nuget\packages\system.speech\8.0.0\lib\net8.0\System.Speech.dll</HintPath>
    </Reference>
    <Reference Include="Markdig.Wpf">
      <HintPath>C:\Users\l1763\.nuget\packages\markdig.wpf\0.5.0.1\lib\netcoreapp3.1\Markdig.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Markdig">
      <HintPath>C:\Users\l1763\.nuget\packages\markdig\0.22.0\lib\netstandard2.0\Markdig.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.web.webview2\1.0.2651.64\lib\net462\Microsoft.Web.WebView2.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Wpf">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.web.webview2\1.0.2651.64\lib\net462\Microsoft.Web.WebView2.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.WinForms">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.web.webview2\1.0.2651.64\lib\net462\Microsoft.Web.WebView2.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Client">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.signalr.client\8.0.8\lib\net8.0\Microsoft.AspNetCore.SignalR.Client.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Client.Core">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.signalr.client.core\8.0.8\lib\net8.0\Microsoft.AspNetCore.SignalR.Client.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Common">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.signalr.common\8.0.8\lib\net8.0\Microsoft.AspNetCore.SignalR.Common.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Protocols.Json">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.signalr.protocols.json\8.0.8\lib\net8.0\Microsoft.AspNetCore.SignalR.Protocols.Json.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Connections.Client">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.http.connections.client\8.0.8\lib\net8.0\Microsoft.AspNetCore.Http.Connections.Client.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Connections.Common">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.http.connections.common\8.0.8\lib\net8.0\Microsoft.AspNetCore.Http.Connections.Common.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Connections.Abstractions">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.aspnetcore.connections.abstractions\8.0.8\lib\net8.0\Microsoft.AspNetCore.Connections.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Features">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.features\8.0.8\lib\net8.0\Microsoft.Extensions.Features.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.logging\8.0.0\lib\net8.0\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.logging.abstractions\8.0.1\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Options">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.options\8.0.2\lib\net8.0\Microsoft.Extensions.Options.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Primitives">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.extensions.primitives\8.0.0\lib\net8.0\Microsoft.Extensions.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Pipelines">
      <HintPath>C:\Users\l1763\.nuget\packages\system.io.pipelines\8.0.0\lib\net8.0\System.IO.Pipelines.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>C:\Users\l1763\.nuget\packages\system.text.json\8.0.4\lib\net8.0\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Channels">
      <HintPath>C:\Users\l1763\.nuget\packages\system.threading.channels\8.0.0\lib\net8.0\System.Threading.Channels.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Bcl.AsyncInterfaces">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.bcl.asyncinterfaces\8.0.0\lib\net8.0\Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Bcl.TimeProvider">
      <HintPath>C:\Users\l1763\.nuget\packages\microsoft.bcl.timeprovider\8.0.1\lib\net8.0\Microsoft.Bcl.TimeProvider.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.DiagnosticSource">
      <HintPath>C:\Users\l1763\.nuget\packages\system.diagnostics.diagnosticsource\8.0.0\lib\net8.0\System.Diagnostics.DiagnosticSource.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>C:\Users\l1763\.nuget\packages\system.memory\4.5.5\lib\netstandard2.1\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>C:\Users\l1763\.nuget\packages\system.runtime.compilerservices.unsafe\6.0.0\lib\net6.0\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Tasks.Extensions">
      <HintPath>C:\Users\l1763\.nuget\packages\system.threading.tasks.extensions\4.5.4\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>C:\Users\l1763\.nuget\packages\system.buffers\4.5.1\lib\netstandard2.0\System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>C:\Users\l1763\.nuget\packages\system.numerics.vectors\4.5.0\lib\netcoreapp2.0\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Encodings.Web">
      <HintPath>C:\Users\l1763\.nuget\packages\system.text.encodings.web\8.0.0\lib\net8.0\System.Text.Encodings.Web.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Users\l1763\.nuget\packages\communitytoolkit.mvvm\8.2.2\analyzers\dotnet\roslyn4.3\cs\CommunityToolkit.Mvvm.SourceGenerators.dll" />
    <Analyzer Include="C:\Users\l1763\.nuget\packages\communitytoolkit.mvvm\8.2.2\analyzers\dotnet\roslyn4.3\cs\CommunityToolkit.Mvvm.CodeFixers.dll" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
</Project>
